### ISSUE TITLE
CSS: Overwritten property value

### ISSUE THREAD

**Issue by delirious-lettuce** [iadgov/WALKOFF#132]
I'm not sure if this is on purpose but PyCharm is warning that the `height` and `width` values are being overwritten.

```css
/* server/templates/pages/playbook/index.html */

#parametersBar{
    height: 651px; /* == 700 minus 49 (where 49 is the height of the tab) */
    width: 450px;
    display: inline-block;
    vertical-align: top;
    height: 700px;  /* this overwrites the height above */
    width: 400px;  /* this overwrites the width above */
    overflow-y:auto;
    background-color:#f5f5f5;
}
```
